### ISSUE TITLE
It shows a very bad designs. not workin g like demo. css seems broken.. 

### ISSUE THREAD

**Issue by hkmsadek** [PygmySlowLoris/vue-notify-me#2]
Why css is not working as demo? is there any special things were used for the demo?

**Comment by Edujugon** [comment]
Hi @hkmsadek ,

The demo is using bulma as css dependency.
Actually this package is open enough to use any css framework you want to use but if you wanna keep the same styling as the demo try to add the bellow stylesheet reference to your code:

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.4/css/bulma.min.css">
```

Let me know if that worked for you

**Comment by Edujugon** [comment]
Hi @hkmsadek ,

I'm closing this issue since I suppose you were able solve it. If that wasn't the case, you may reopen it anytime with more details.
